apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-app-deployment
  labels:
    app: management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-app
  template:
    metadata:
      labels:
        app: management-app
    spec:
      containers:
      - name: management-app
        image: your-repo/management-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: management-app-service
spec:
  selector:
    app: management-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
